#ifndef NLRE_DX11_INPUT_LAYOUT_DESCRIPTIONS_
#define NLRE_DX11_INPUT_LAYOUT_DESCRIPTIONS_

static const NLRE_APIInputLayoutDecs forwardPosNormTanTextDesc[] = {
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "NORMAL", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TANGENT", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 24, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TEXCOORDS0", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 36, D3D11_INPUT_PER_VERTEX_DATA, 0 },
};

static const NLRE_APIInputLayoutDecs forwardPosTextDesc[] = {
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TEXCOORDS0", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0 },
};

NLRE_InputLayoutDesc forwardPosNormTanText(forwardPosNormTanTextDesc, 4);
NLRE_InputLayoutDesc forwardPosText(forwardPosTextDesc, 2);

#endif