#ifndef NLRE_DX11_INPUT_LAYOUT_DESCRIPTIONS_
#define NLRE_DX11_INPUT_LAYOUT_DESCRIPTIONS_

static const NLRE_APIInputLayoutDecs defaultLayout[] = {
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "NORMAL", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 1, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
};

NLRE_InputLayoutDesc defaultL(defaultLayout,3);

#endif